spring:
  datasource:
    url: jdbc:h2:mem:raspberrydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console   # define o caminho do console
  jpa:
    hibernate:
      ddl-auto: create   # pode usar 'update' se quiser manter dados entre reinícios
    show-sql: true
    properties:
      hibernate:
        format_sql: true
